# Generated by Django 3.0.7 on 2020-06-09 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_album', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('Name', models.CharField(max_length=20, null=True)),
                ('Otchestvo', models.CharField(max_length=20, null=True)),
                ('Phone', models.CharField(max_length=20, null=True)),
                ('Surname', models.CharField(max_length=20, null=True)),
                ('name_class', models.CharField(max_length=20, null=True)),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3, null=True)),
                ('name_class', models.CharField(max_length=20, null=True)),
                ('time_class', models.CharField(max_length=20, null=True)),
                ('week_day', models.CharField(max_length=20, null=True)),
                ('id_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=None)),
                ('id_name_of_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Albums')),
            ],
        ),
    ]
