# Generated by Django 3.0.7 on 2020-06-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='id_teacher',
        ),
        migrations.AddField(
            model_name='schedule',
            name='id_teacher_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
