# Generated by Django 3.0.7 on 2020-06-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_hotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='id_name_of_album',
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Albums',
        ),
    ]
